# Generated by Django 3.0.8 on 2020-08-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20200824_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nutrution_grade_fr',
            new_name='nutrition_grade_fr',
        ),
    ]
