# Generated by Django 3.1.1 on 2020-09-21 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_auto_20200907_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="substitute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fk_product_substitute",
                to="catalog.product",
                unique=True,
            ),
        ),
    ]
