# Generated by Django 3.1.1 on 2020-09-21 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_auto_20200921_0702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="substitute",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
            ),
        ),
    ]
