# Generated by Django 3.1.1 on 2020-09-21 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0013_auto_20200921_0706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="substitute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fk_product_substitute",
                to="catalog.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("substitute", "user")},
        ),
    ]
